improve build command

diff --git a/dockerfiles/alpine/Dockerfile b/dockerfiles/alpine/Dockerfile
--- a/dockerfiles/alpine/Dockerfile
+++ b/dockerfiles/alpine/Dockerfile
@@ -6,9 +6,12 @@ ENV DOCKER_HOST='tcp://docker:2375'
 
 ENV GITLAB_RUNNER_VERSION v10.0.0
 
-RUN adduser -D -S -h /home/gitlab-runner gitlab-runner
+COPY checksums.sha256 /tmp/
+COPY entrypoint /
 
-RUN apk add --update \
+RUN adduser -D -S -h /home/gitlab-runner gitlab-runner \
+    # Install packages
+    && apk add --no-cache --update \
     bash \
     ca-certificates \
     git \
@@ -20,69 +23,61 @@ RUN apk add --update \
     e2fsprogs-extra \
     iptables \
     xfsprogs \
-    xz
-
-
-
-COPY checksums.sha256 /tmp/
-
-RUN wget  https://gitlab-runner-downloads.s3.amazonaws.com/$GITLAB_RUNNER_VERSION/binaries/gitlab-runner-linux-amd64 -O /usr/bin/gitlab-runner && \
-    chmod +x /usr/bin/gitlab-runner && \
-    ln -s /usr/bin/gitlab-runner /usr/bin/gitlab-ci-multi-runner && \
-    gitlab-runner --version && \
-    mkdir -p /etc/gitlab-runner/certs && \
-    chmod -R 700 /etc/gitlab-runner
-
-RUN wget  https://github.com/docker/machine/releases/download/v0.12.2/docker-machine-Linux-x86_64 -O /usr/bin/docker-machine && \
-    chmod +x /usr/bin/docker-machine && \
-    docker-machine --version
-
-RUN wget  https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 -O /usr/bin/dumb-init && \
-    chmod +x /usr/bin/dumb-init && \
-    dumb-init --version
-
-RUN sha256sum -c -w /tmp/checksums.sha256
-
-# Install docker
-RUN set -ex; \
-# why we use "curl" instead of "wget":
-# + wget -O docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-17.03.1-ce.tgz
-# Connecting to download.docker.com (54.230.87.253:443)
-# wget: error getting response: Connection reset by peer
-    apk add --no-cache --virtual .fetch-deps \
-        curl \
-        tar \
-    ; \
-    \
-# this "case" statement is generated via "update.sh"
-    apkArch="$(apk --print-arch)"; \
-    case "$apkArch" in \
-        x86_64) dockerArch='x86_64' ;; \
-        aarch64) dockerArch='aarch64' ;; \
-        ppc64le) dockerArch='ppc64le' ;; \
-        s390x) dockerArch='s390x' ;; \
-        *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
-    esac; \
-    \
-    if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
-        echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
-        exit 1; \
-    fi; \
-    \
-    tar --extract \
-        --file docker.tgz \
-        --strip-components 1 \
-        --directory /usr/local/bin/ \
-    ; \
-    rm docker.tgz; \
-    \
-    apk del .fetch-deps; \
-    \
-    dockerd -v; \
-    docker -v
-
-COPY entrypoint /
-RUN chmod +x /entrypoint
+    xz \
+    # Install gitlab runner
+    && wget  https://gitlab-runner-downloads.s3.amazonaws.com/$GITLAB_RUNNER_VERSION/binaries/gitlab-runner-linux-amd64 -O /usr/bin/gitlab-runner \
+    && chmod +x /usr/bin/gitlab-runner \
+    && ln -s /usr/bin/gitlab-runner /usr/bin/gitlab-ci-multi-runner \
+    && gitlab-runner --version \
+    && mkdir -p /etc/gitlab-runner/certs \
+    && chmod -R 700 /etc/gitlab-runner \
+    # Install docker-machine
+    && wget  https://github.com/docker/machine/releases/download/v0.12.2/docker-machine-Linux-x86_64 -O /usr/bin/docker-machine \
+    && chmod +x /usr/bin/docker-machine \
+    && docker-machine --version \
+    # Install dumb-init
+    && wget  https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 -O /usr/bin/dumb-init \
+    && chmod +x /usr/bin/dumb-init \
+    && dumb-init --version \
+    && sha256sum -c -w /tmp/checksums.sha256 \
+    # Install docker
+    && set -ex; \
+    # why we use "curl" instead of "wget":
+    # + wget -O docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-17.03.1-ce.tgz
+    # Connecting to download.docker.com (54.230.87.253:443)
+    # wget: error getting response: Connection reset by peer
+        apk add --no-cache --virtual .fetch-deps \
+            curl \
+            tar \
+        ; \
+        \
+    # this "case" statement is generated via "update.sh"
+        apkArch="$(apk --print-arch)"; \
+        case "$apkArch" in \
+            x86_64) dockerArch='x86_64' ;; \
+            aarch64) dockerArch='aarch64' ;; \
+            ppc64le) dockerArch='ppc64le' ;; \
+            s390x) dockerArch='s390x' ;; \
+            *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+        esac; \
+        \
+        if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+            echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+            exit 1; \
+        fi; \
+        \
+        tar --extract \
+            --file docker.tgz \
+            --strip-components 1 \
+            --directory /usr/local/bin/ \
+        ; \
+        rm docker.tgz; \
+        \
+        apk del .fetch-deps; \
+        \
+        dockerd -v; \
+        docker -v \
+        chmod +x /entrypoint
 
 VOLUME ["/etc/gitlab-runner", "/home/gitlab-runner", "/var/lib/docker"]
 
